#!/command/with-contenv sh

export PATH=/opt/pyload/bin:${PATH}

. /opt/pyload/bin/activate

exec s6-setuidgid appuser pyload --userdir=/config --storagedir=/downloads --tempdir=/temporary-downloads

