#!/command/with-contenv sh

export PATH=/opt/pyload/bin:${PATH}
export HOME=/config

. /opt/pyload/bin/activate

cd /config

exec s6-setuidgid appuser pyload --userdir=/config --storagedir=/downloads --tempdir=/temporary-downloads
