FROM alpine:3.11
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='pyload' \
    APPUID='10005' \
    APPGID='10005' \
    PYCURL_SSL_LIBRARY='openssl'

### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER="${APPUSER}" && \
    MYUID="${APPUID}" && \
    MYGID="${APPGID}" && \
    ConfigureUser && \
    apk upgrade --no-cache && \
    apk --no-cache upgrade && \
    apk add --no-cache --virtual=build-deps \
      make \
      gcc \
      g++ \
      python2-dev \
      py2-pip \
      libressl-dev \
      curl-dev \
      musl-dev \
      libffi-dev \
      jpeg-dev \
      git \
      zlib-dev \
      py-pip  \
    && \
    pip --no-cache-dir install --upgrade \
      pip \
      setuptools \
      wheel \
    && \
    pip --no-cache-dir install --upgrade \
      beaker \
      BeautifulSoup \
      feedparser \
      jinja2 \
      Pillow \
      pycrypto \
      pycurl \
      pyopenssl \
      tesseract \
      spidermonkey \
      thrift \
    && \
    git clone --depth 1 https://github.com/pyload/pyload.git -b stable /opt/pyload && \
    apk del --no-cache --purge \
      build-deps  && \
    apk add --no-cache --virtual=run-deps \
      bash \
      jpeg \
      libffi \
      libcurl \
      mailx \
      python2 \
      ssmtp \
      su-exec \
      tesseract-ocr \
      unrar \
      unzip \
      zlib \
    && \
    mkdir -p /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /opt/pyload/.git \
           /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*


### Volume
VOLUME ["/downloads","/config"]

### Expose ports
EXPOSE 8000 7227 9666

### Running User: not used, managed by docker-entrypoint.sh
#USER pyload

### Start pyload
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["pyload"]

