ARG PYLOAD_VERSION='0.5.0b3.dev91'
ARG UNRAR_VERSION='6.2.12'

FROM digrouz/alpine-s6:latest as builder

ARG PYLOAD_VERSION
ARG UNRAR_VERSION

ENV PYLOAD_VERSION="${PYLOAD_VERSION}"\
    UNRAR_VERSION="${UNRAR_VERSION}"

RUN set -x && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      curl \
      curl-dev \
      gcc \
      g++ \
      make \
      musl-dev \
      py3-pip \
      py3-virtualenv \
      python3-dev \
    && \
    cd /opt && \
    virtualenv pyload && \
    cd pyload && \
    . bin/activate && \
    pip --no-cache-dir install --upgrade \
      pip \
      setuptools \
      wheel \
    && \
    pip --no-cache-dir install --upgrade \
      pyload-ng[all]==${PYLOAD_VERSION} \
    && \
    curl -SsL https://www.rarlab.com/rar/unrarsrc-${UNRAR_VERSION}.tar.gz -o /tmp/unrar.tar.gz && \
    cd /tmp && \
    tar xzf /tmp/unrar.tar.gz && \
    cd unrar && \
    make -f makefile && \
    chmod 755 unrar

FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG PYLOAD_VERSION
ARG UNRAR_VERSION

### Environment variables
ENV PYLOAD_VERSION="${PYLOAD_VERSION}"\
    UNRAR_VERSION="${UNRAR_VERSION}"

### Copy config files
COPY root/ /
COPY --from=builder /opt/pyload /opt/pyload
COPY --from=builder /tmp/unrar/unrar /usr/bin/unrar

### Install Application
RUN set -x && \
    apk --no-cache upgrade && \
    chown -R appuser /opt/pyload && \
    apk add --no-cache --virtual=run-deps \
      libcurl \
      mailx \
      python3 \
      ssmtp \
      unzip \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*

### Volume
VOLUME ["/downloads","/config","/temporary-downloads"]

### Expose ports
EXPOSE 8000 7227 9666

